-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25/01/2018 19:32:10
-- Server version: 5.5.5-10.1.19-MariaDB
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE gestortareas;

--
-- Definition for table tareas
--
DROP TABLE IF EXISTS tareas;
CREATE TABLE tareas (
  id_tarea INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  categoria VARCHAR(255) NOT NULL,
  prioridad VARCHAR(255) NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  propietario VARCHAR(255) NOT NULL,
  PRIMARY KEY (id_tarea),
  INDEX FK_tareas_user_username (propietario)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

--
-- Definition for table usuarios
--
DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) DEFAULT NULL,
  apellidos VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) NOT NULL,
  username VARCHAR(255) NOT NULL,
  authKey VARCHAR(255) DEFAULT NULL,
  activo TINYINT(1) DEFAULT 0,
  password VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_usuarios_email (email),
  UNIQUE INDEX UK_usuarios_nombre (nombre),
  UNIQUE INDEX UK_usuarios_username (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

-- 
-- Dumping data for table tareas
--
INSERT INTO tareas VALUES
(1, 'Comprar', 'comida semanal', 'personal', 'ALTA', '2018-01-23', '2018-01-25', 'silvia'),
(2, 'Comprar', 'comida perro', 'personal', 'MEDIA', '2018-01-26', '2018-01-26', 'silvia'),
(3, 'proyecto', 'gestor de tareas yii2', 'clase', 'alta', '0000-00-00', '0000-00-00', 'silvia'),
(4, 'proyecto', 'gestor de tareas yii2', 'clase', 'alta', '0000-00-00', '0000-00-00', 'silvia'),
(5, 'proyecto', 'gestor de tareas yii2', 'clase', 'alta', '2018-01-25', '2018-01-31', 'silvia');

-- 
-- Dumping data for table usuarios
--
INSERT INTO usuarios VALUES
(1, 'silvia', NULL, 'silvia.gomeza@gmail.com', 'silvia', '_4niJ3zc8RFlw1zYdFTqnacwb_lZo9Gj', 1, '$2y$13$XAY6yfSq1ZUBjdJWBLZLN.tBhkarfAe0ZLp97CQAlshK1nDE9GLG6'),
(2, 'Efi', 'arce', 'efigenia.arsan@gmail.com', 'efi', 'YOlsM5aXDymdS-tlaEWb3U0C_g-h8rS_', 0, '$2y$13$7VhmLrWt5mVoP19XMAUHSu9yunpcqfYs9quDxNCHxzgIESJINhI7S');

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;